name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data preprocessing
      run: |
        python scripts/data_preprocessing.py

    - name: Upload preprocessed data
      uses: actions/upload-artifact@v2
      with:
        name: preprocessed-data
        path: data/preprocessed_old_matches.csv,data/preprocessed_new_matches.csv

    - name: Run feature engineering
      run: |
        python scripts/feature_engineering.py
