name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data preprocessing
      run: python scripts/data_preprocessing.py

    - name: Upload preprocessed data
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-data
        path: |
          data/preprocessed_old_matches.csv
          data/preprocessed_new_matches.csv

    - name: Run feature engineering
      run: python scripts/feature_engineering.py

    - name: Upload feature-engineered data
      uses: actions/upload-artifact@v4
      with:
        name: feature-engineered-data
        path: |
          data/fe_old_matches.csv
          data/fe_new_matches.csv

    - name: Run model training
      run: python scripts/model_training.py

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: prediction_model
        path: |
          data/voting_classifier.pkl

    - name: Set environment variables for prediction
      run: |
        echo "HOME_TEAM=manchester utd" >> $GITHUB_ENV
        echo "AWAY_TEAM=fulham" >> $GITHUB_ENV
        echo "MATCH_DATE=2024-08-16" >> $GITHUB_ENV
        echo "SEASON_END_YEAR=2025" >> $GITHUB_ENV

    - name: Run prediction
      run: python scripts/predict_match.py
