name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Data Preprocessing
      run: |
        python scripts/data_preprocessing.py

    - name: Feature Engineering
      run: |
        python scripts/feature_engineering.py

    - name: Model Training
      run: |
        python scripts/model_training.py

    - name: Model Evaluation
      run: |
        python scripts/model_evaluation.py

    - name: Run Tests
      run: |
        pip install pytest
        pytest tests/
