name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  evaluate_and_predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.24.4
        pip install -r requirements.txt

    - name: Run model evaluation
      run: python scripts/model_evaluation.py

    - name: Upload evaluation results
      uses: actions/upload-artifact@v4
      with:
        name: evaluation-results
        path: data/evaluation_results.csv

    - name: Set environment variables for prediction
      run: |
        echo "HOME_TEAM=manchestercity" >> $GITHUB_ENV
        echo "AWAY_TEAM=liverpool" >> $GITHUB_ENV

    - name: Run prediction
      run: python scripts/predict_match.py

    - name: Upload prediction results
      uses: actions/upload-artifact@v4
      with:
        name: prediction-results
        path: data/prediction_results.txt
